CREATE TABLE HOUSE(
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(250) NOT NULL,
    LASTNAME VARCHAR(250) NOT NULL,
    EMAIL  VARCHAR(250) NULL,
    TELNUMBER VARCHAR(15) NOT NULL,
    ADDRESS  VARCHAR(250) NOT NULL UNIQUE,
    RESIDENTNUMBER INT(3) NOT NULL,
	FLOORNUMBER INT(2) NOT NULL,
    REVOKEHOUSE CHAR(2) NOT NULL,
    SMOKERSNUMBER INT(3) NOT NULL,
    PETSNUMBER INT(3) NOT NULL,
    FLOORMATERIAL VARCHAR(250) NOT NULL,
    WALLSMATERIAL VARCHAR(250) NOT NULL,
    PAINTTYPE VARCHAR(250) NOT NULL,
    LATITUDE VARCHAR(50),
    ALTITUDE VARCHAR(50),
    PRIMARY KEY(ID)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB;

CREATE TABLE DISPLAY(
    ID BIGINT AUTO_INCREMENT,
    STATE CHAR(2) NOT NULL,
    LASTDATE DATETIME NOT NULL,
    PRIMARY KEY(ID)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB;

CREATE TABLE VARIABLES(
	ID BIGINT AUTO_INCREMENT,
    DATETIME DATETIME NOT NULL,
    CONCENTRATION FLOAT NOT NULL,
    TEMPERATURA FLOAT NOT NULL,
    HUMIDITY FLOAT NOT NULL,
    PRESSURE FLOAT NOT NULL,
    DISPLAY BIGINT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(DISPLAY) REFERENCES DISPLAY(ID) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=INNODB;

CREATE TABLE RT(
	ID BIGINT AUTO_INCREMENT,
    DATETIME DATETIME NOT NULL,
    CONCENTRATION FLOAT NOT NULL,
    TEMPERATURA FLOAT NOT NULL,
    HUMIDITY FLOAT NOT NULL,
    PRESSURE FLOAT NOT NULL,
    DISPLAY BIGINT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(DISPLAY) REFERENCES DISPLAY(ID) ON UPDATE CASCADE ON DELETE CASCADE
)COLLATE='utf8_general_ci'
ENGINE=INNODB;

CREATE TABLE ACTIVITY(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(250),
    PRIMARY KEY(ID)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB;

CREATE TABLE DETAILHOUSE(
    ACTIVITY INT,
    HOUSECODE BIGINT,
    FOREIGN KEY(ACTIVITY) REFERENCES ACTIVITY(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(HOUSECODE) REFERENCES HOUSE(ID) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
    ;

    CREATE TABLE ALARMCONF (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    MIN INT NOT NULL,
    MAX INT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    MESSAGE TEXT NOT NULL,
    PRIMARY KEY(ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE ALARMS (
ID BIGINT NOT NULL AUTO_INCREMENT,
DATETIME DATETIME NOT NULL,
DISPLAY BIGINT NOT NULL,
ALARMCONF BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(DISPLAY) REFERENCES DISPLAY(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(ALARMCONF) REFERENCES ALARMCONF(ID) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE INSTALATION(
    HOUSECODE BIGINT,
    DISPLAY BIGINT,
    INTALLER VARCHAR(15),
    INTALLDATE DATETIME,
    FOREIGN KEY(DISPLAY) REFERENCES DISPLAY(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(HOUSECODE) REFERENCES house(ID) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

INSERT INTO house(NAME,LASTNAME,EMAIL,TELNUMBER,ADDRESS,RESIDENTNUMBER,FLOORNUMBER,REVOKEHOUSE,SMOKERSNUMBER,PETSNUMBER,FLOORMATERIAL,WALLSMATERIAL,PAINTTYPE,LATITUDE,ALTITUDE) VALUES('NOMBRE RESIDENTE','APELLIDO','CORREO','NUMERO','DIRECCION',4,2,'SI',1,2,'MATERIAL DEL PISO','MATERIAL DE PAREDES','TIPO DE PINTURA','LATITUD','ALTITUD');
